### ISSUE TITLE
英文博客标题

### ISSUE THREAD

**Issue by xjtu-blacksmith** [zchen9/hexo-theme-hollow#39]
问题 #30 提及了中文标题太长的问题。这里对英文标题有类似疑问，建议作者在样式表预处理代码内加入实现

``` css
.post-preview > a > .post-title {
    word-wrap: break-word;
}
```

的语句，以实现首页上英文标题长单词的自动换行。
