### ISSUE TITLE
toc.styl的一处样式兼容性问题

### ISSUE THREAD

**Issue by fakeyanss** [zchen9/hexo-theme-hollow#46]
在包含三级以上标题时，当前的样式会导致二级和三级标题重叠

![image](https://user-images.githubusercontent.com/30440198/116277136-c6237b80-a7b7-11eb-823a-cdec662b2543.png)

[view file](https://github.com/zchen9/hexo-theme-hollow/blob/f762cecdd1676a3ae7de610faa01cc282603dc63/source/css/toc.styl#L40)

注释掉可修复该问题。

```css
#article-toc-inner .toc-item {
    // height: 2em;
    line-height: 2em;
    padding: 0;
    margin: 0;
}
```
