### ISSUE TITLE
toc序号怎么去掉？

### ISSUE THREAD

**Issue by He1o** [zchen9/hexo-theme-hollow#53]
![image](https://user-images.githubusercontent.com/57656907/142346165-ffbef881-b12f-4d84-bc24-b0464d52e2de.png)
![image](https://user-images.githubusercontent.com/57656907/142346186-7285b0c3-15f4-4191-8734-f4e9ed8b94c2.png)
一共三个序号，我把list_number改为false第二个就没了
第三个是我自己的
可第一个序号怎么才能去掉？

**Comment by AtomAlpaca** [comment]
这个其实涉及`css`中`ol`，即有序列表的样式问题，需要在`hollow/source/css/toc.styl`中设置
找到以下这一段
``` css
#article-toc-inner .toc-item {
    height: 2em;
    line-height: 2em;
    padding: 0;
    margin: 0;
}
```
在这里可以统一设置所有列表的样式，如果想要去掉，需要加上`list-style-type: none;`，即改为
``` css
#article-toc-inner .toc-item {
    list-style-type: none;
    height: 2em;
    line-height: 2em;
    padding: 0;
    margin: 0;
}
```
效果预览：
![Test](https://user-images.githubusercontent.com/66774326/142618364-417df44f-8ae3-49e2-be19-9b8571633dce.png)

@He1o
